"""
Create a class, using AsyncClient, that will be responsible for fetching data from the GitHub API 
Partial code such as initializing the client, setting the base URL, and setting the headers is generated by CHATGPT.
"""

import httpx
from app.core.config import settings

class GitHubAPIClient:

    def __init__(self):
        self.base_url = "https://api.github.com"
        self.headers = {}
        if settings.GITHUB_API_TOKEN:
            self.headers["Authorization"] = f"token {settings.GITHUB_API_TOKEN}"
        self.client = httpx.AyncClient(headers=self.headers, base_url=self.base_url)

    async def fetch_user_projects(self, username:str):
        pass 


    async def close(self):
        await self.client.aclose()

